[env:4d_systems_esp32s3_gen4_r8n16]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino

; =========================================
; TỐC ĐỘ & CẤU HÌNH PHẦN CỨNG (CPU / FLASH)
; =========================================
upload_speed = 921600
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio

; Phân vùng: 16M Flash (3MB APP/9.9MB FATFS)
board_build.partitions = default_16MB.csv

; =========================================
; CỜ BIÊN DỊCH (TƯƠNG ĐƯƠNG MENU TOOLS)
; =========================================
build_flags =
    ; Bật OPI PSRAM
    -D BOARD_HAS_PSRAM
    
    ; Chạy Arduino & Events trên Core 1
    -D ARDUINO_RUNNING_CORE=1
    -D ARDUINO_EVENT_RUNNING_CORE=1

; =========================================
; QUẢN LÝ THƯ VIỆN TỰ ĐỘNG (LIB_DEPS)
; =========================================
lib_deps =
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    madhephaestus/ESP32Servo @ ^3.2.1
    adafruit/Adafruit MCP23017 Arduino Library @ ^2.3.2
    bblanchon/ArduinoJson @ ^7.4.3
    tzapu/WiFiManager @ ^2.0.17

; =========================================
; CẤU HÌNH NẠP CODE QUA LOCAL OTA (WIFI)
; =========================================
upload_protocol = espota
upload_port = 172.16.55.244  ; Thay bằng IP hiển thị trên LCD (IP mà wifi cấp cho ESP32)

